name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "hello, thank you for making an issue. somebody else will probably help with the issue."
        pr-message: "hello, thanking for helping supply the wordbank with stuff. Euan or another maintainer will review the changes and add them (probably)"
